### ISSUE TITLE
Could you add 8.6.2 sdk?

### ISSUE THREAD

**Issue by DenisKaminsky** [FontoXML/fontoxml-table-flow-cals#1]
8.6.2 is not available in "Tags". Could you add it?

**Comment by DenisKaminsky** [comment]
is it the same as 8.5.2?

**Comment by bwrrp** [comment]
Oops, it looks like we forgot to push the tags for the 8.6.x releases. I'll see if we can get that fixed. In the meantime, you can use the code from commit b95536d63f91eea1dc59771cb6f427995fc37446, which should work for all 8.6.x versions.

**Comment by mmeij** [comment]
The missing tags have been added retroactively. Thanks for reporting @DenisKaminsky.
